### ISSUE TITLE
Rust documentation

### ISSUE THREAD

**Issue by fwuermseher** [E-MAB/GMAB#47]
## PyO3 <-> docs.rs Compatiblity

It may be necessary to disable pyo3 and/or disable pyo3 for bindings to enable docs.rs sucessfully

```toml
[package.metadata.docs.rs]
features = ["extension-module"]
rustdoc-args = ["--cfg", "docsrs"]
```

```rust
// in pygmab lib.rs
#[cfg(not(docsrs))]
use pyo3::prelude::*;
```

## We should additionally link the python docs in rs.

```toml
[package]
documentation = "https://your-sphinx-docs-url.com"
```

```rust
// Reference the python docs somewhere in rust doc comments.

/// Rust-side documentation
///
/// For the Python API, see [Python Docs](https://your-sphinx-docs-url.com).
```
